"""add_split_assets_to_jobs

Revision ID: 31e7dad3f86a
Revises: 
Create Date: 2026-05-28 10:10:41.641256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '31e7dad3f86a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('video_only_path', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('vocals_path', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('accompaniment_path', sa.String(), nullable=True))
    op.add_column('jobs', sa.Column('subtitle_path', sa.String(), nullable=True))
    
    # Custom: Add new value to PostgreSQL jobstatus enum
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        # Check current enum values
        result = bind.execute(sa.text("SELECT enum_range(NULL::jobstatus)"))
        enum_range = result.scalar()
        if enum_range is not None:
            if 'READY_FOR_ANALYSIS' not in enum_range:
                op.execute("ALTER TYPE jobstatus ADD VALUE 'READY_FOR_ANALYSIS'")
            if 'ready_for_analysis' not in enum_range:
                op.execute("ALTER TYPE jobstatus ADD VALUE 'ready_for_analysis'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'subtitle_path')
    op.drop_column('jobs', 'accompaniment_path')
    op.drop_column('jobs', 'vocals_path')
    op.drop_column('jobs', 'video_only_path')
    # ### end Alembic commands ###
